name = "blog"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
routes = [{ pattern = "blog.kali-team.cn/*", zone_id = "28eeca2e15ad32083050e97611262653" }]
usage_model = "bundled"
account_id = "8c8c6f1b283ead190a0a4315af426428"
[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
ACCOUNT_ID = "8c8c6f1b283ead190a0a4315af426428"
MY_DOMAIN = "frany.dev"
NOTION_DOMAIN = "silken-badger-e39.notion.site"
PAGE_MAP = '{"/":"755e8a8cdf604c719b6179c817d6fb67"}'
ICON_URL = "https://avatars.githubusercontent.com/u/61435815?v=4"

[placement]
mode = "smart"
